#PLEASE USE %player% TO INPUT THE PLAYER'S NAME PLACEHOLDER


#Sets the Join Message that is sent only to the player that has joined
PlayerJoinMessage: "&eWelcome to the server, %player%"

#Sets the Public Join Message that is sent to the whole server
PublicJoinMessage: "&e%player% has joined the server"

#Sets the Public Leave Message that is sent to the whole server
PublicLeaveMessage: "&e%player% has left the server"